# DO NOT CHANGE ANYTHING
version: '3'

services:
  web:
    hostname: web
    container_name: 11lh_web
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
  api:
    hostname: api
    container_name: 11lh_api
    image: ElevenLabsHackathon/api
    build:
      context: ./api
    volumes:
      - ./api:/app
    # Unnecessary as the API is reverse-proxied through Nginx
    # ports:
    #   - "8000:8080"